services:
  frontend:
    build: ./frontend
    volumes:
      - static:/frontend/dist
      - ./frontend:/frontend
      - /frontend/node_modules

  app:
    build: ./backend
    volumes:
      - ./backend/:/app
      - static:/app/dist
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  static:
